config/routes.rb
Rails.application.routes.draw do
  resources :periods, except: [:new] do
    collection do
      get 'new/:user_id', :to => "periods#new", :as => 'new'
      post 'status/(:token)', :to => "periods#order_status", :as => 'order_status'
      post 'refund/(:token)', :to => "periods#order_refund", :as => 'order_refund'
      post 'tracking/(:token)', :to => "periods#order_tracking", :as => 'order_tracking'
      post 'message/(:token)', :to => "periods#send_comment", :as => 'send_comment'
    end
  end

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users

  get '/dashboard' => "dashboard#index", as: :user_root
  get '/order/:id' => "dashboard#order", as: :order_dashboard
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action(only: [:order]) do |c|
    set_order unless c.request.format.json?
  end

  # GET /dashboard
  def index
    unless current_user.admin
      @orders = snipcart_request('orders')['items'].select { |v|
        DateTime.parse(v['creationDate']) >= current_user.periods.last.start_date.beginning_of_day &&
        DateTime.parse(v['creationDate']) <= current_user.periods.last.end_date.end_of_day
      }
    else
      @orders = snipcart_request('orders')['items']
    end
    @orders_without_refund = @orders.select { |v|
      v['refunds'].length <= 0
    }
  end

  # GET /order/:id
  def order
    respond_to do |format|
      format.html {
        render :order
      }
      format.json {
        @order = snipcart_request('orders')['items'].select {|v| v['invoiceNumber'].downcase == params[:id].downcase}[0]
        publicAPI(@order)
      }
    end
  end

  private

  def set_order
    @order = snipcart_request('orders')['items'].select {|v| v['token'] == params[:id]}[0]
    unless current_user.admin
      start = DateTime.parse(@order['creationDate']) >= current_user.periods.last.start_date.beginning_of_day
      stop = DateTime.parse(@order['creationDate']) <= current_user.periods.last.end_date.end_of_day
      if start == true && stop == true
        return @order
      else
        redirect_to user_root_url, notice: "Vous n'avez pas accès à cette commande"
      end
    end
  end
end

app/views/dashboard/index.html.erb
<div id="dashboard">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title"><%= @orders_without_refund.sum {|v| v['items'][0]['price'].to_f}.round(2) %></h2>
            <p class="card-text">Chiffre d'affaire</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title"><%= @orders_without_refund.select {|v| v['status'] == 'Processed'}.count %></h2>
            <p class="card-text">Nouvelles commandes</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title"><%= @orders_without_refund.count %></h2>
            <p class="card-text">Commandes totales (hors remboursées)</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container last-orders">
    <h2>Dernières commandes</h2>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">Statut</th>
            <th scope="col">Date</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <th scope="row"><%= order['invoiceNumber'] %></th>
              <td><%= order['email'] %></td>
              <td><%= status_translate(order['status']) %> <%= '- Remboursée' if order['refunds'].length > 0 %></td>
              <td><%= DateTime.parse(order['creationDate']).strftime('%d/%m/%Y') %></td>
              <td><%= link_to 'Voir', order_dashboard_path(order['token']) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/dashboard/order.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <br><br>
      <div class="jumbotron">
        <h1 class="display-4">#<%= @order['invoiceNumber'] %></h1>
        <h3 class="display-6"><%= @order['user']['billingAddressName'] %> - <%= DateTime.parse(@order['user']['creationDate']).strftime('%d/%m/%Y') %></h3>
          <%= form_tag order_status_periods_path(@order['token']), remote: :true, method: :post do %>
            <div class="input-group">
              <%= select_tag 'status', options_for_select(status_translate
                    .invert
                    .to_a,
                  selected: @order['status']),
                  class: 'custom-select' %>
              <div class="input-group-append">
                <input class="btn btn-success" type="submit" value="Valider">
              </div>
            </div>
          <% end %>
        <hr class="my-4">
        <% if @order['status'].downcase == 'shipped'.downcase %>
          <h3 class="display-6">Suivi de colis</h3>
            <%= form_tag order_tracking_periods_path(@order['token']), remote: :true, method: :post do %>
              <div class="input-group">
                <%= hidden_field_tag 'id', @order['invoiceNumber'] %>
                <%= select_tag 'trackingUrl', options_for_select(tracking_url,
                    selected: @order['trackingUrl'] ||= current_user.tracking_url),
                    class: 'custom-select' %>
                <%= text_field_tag 'trackingNumber', @order['trackingNumber'] ||= nil, placeholder: 'Numéro de suivi' %>
                <div class="input-group-append">
                  <input class="btn btn-success" type="submit" value="Valider">
                </div>
              </div>
            <% end %>
          <hr class="my-4">
        <% end %>
        <h3 class="display-6"><%= @order['finalGrandTotal'] %>€ - <%= @order['items'].count %> élément(s) dans le panier</h3><br>
        <table class="table table-bordered table-light">
          <thead>
            <tr>
              <td scope="col">Nom</td>
              <td scope="col">Quantité</td>
              <td scope="col">Autres</td>
            </tr>
          </thead>
          <tbody>
            <% @order['items'].each do |order| %>
              <tr>
                <td><%= link_to order['name'], order['url'], target: '_blank' %></td>
                <td><%= order['quantity'] %></td>
                <td>
                  <% order['customFields'].each do |f| %>
                  <%= f['name'] %> :
                  <%= f['displayValue'] %><br>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% if @order['refunds'].length > 0 %>
          <hr class="my-4">
          <h3 class="display-6">Remboursements</h3>
          <table class="table table-bordered table-light">
            <thead>
              <tr>
                <td scope="col">Montant</td>
                <td scope="col">Message</td>
                <td scope="col">Date</td>
              </tr>
            </thead>
            <tbody>
              <% @order['refunds'].each do |refund| %>
                <tr>
                  <td><%= refund['amount'] %></td>
                  <td><%= refund['comment'] %></td>
                  <td><%= DateTime.parse(refund['creationDate']).strftime('%d/%m/%Y - %Hh%M') %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
        <hr class="my-4">
        <p>
          <h3 class="display-6">Adresse destinataire</h3>
          <%= @order['user']['shippingAddressName'] %><br>
          <%= @order['user']['shippingAddressAddress1'] %><br>
          <%= @order['user']['shippingAddressAddress2'] %><br>
          <%= @order['user']['shippingAddressPostalCode'] %> - <%= @order['user']['shippingAddressCity'] %><br>
          <%= @order['user']['shippingAddressCountry'] %>
        </p>
        <hr class="my-4">
        <p>
          <% unless @order['user']['shippingAddressSameAsBilling'] %>
            <div class="alert alert-warning" role="alert">
              L'adresse du destinataire n'est pas la même que l'adresse du payeur.
              <b>Il s'agit peut-être d'une surprise</b>
            </div>
            <h3 class="display-6">Contact payeur</h3>
            <a href="tel:<%= @order['user']['shippingAddressPhone'] %>">
              <%= @order['user']['shippingAddressPhone'] %><br>
            </a>
            <%= mail_to @order['user']['email'] %>
          <% end %>
          <h3 class="display-6">Contact destinataire</h3>
          <a href="tel:<%= @order['user']['billingAddressPhone'] %>">
            <%= @order['user']['billingAddressPhone'] %><br>
          </a>
          <% if @order['user']['shippingAddressSameAsBilling'] %>
            <%= mail_to @order['user']['email'] %>
          <% end %>
        </p>
        <hr class="my-4">
        <h3 class="display-6">Action zone</h3>
        <!-- <%= link_to 'Télécharger la facture', '/', class: "btn btn-warning" %> -->
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#contact">Contacter le client</button>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#refund">Rembourser</button>
        <hr class="my-4">
        <h3 class="display-6">Notifications</h3>
        <ul>
          <% snipcart_request('orders/' + @order['token'] + '/notifications')['items'].each do |notif| %>
            <li>
              <b>Date :</b> <%= DateTime.parse(notif['creationDate']).strftime('%d/%m/%Y') %><br>
              <b>Type :</b> <%= notif['type'] %><br>
              <b>Message :</b> <%= notif['message'] %><br><br>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="refund" tabindex="-1" role="dialog" aria-labelledby="Rembourser" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Rembourser</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag order_refund_periods_path, method: :post, remote: true do %>
          <%= hidden_field_tag 'token', @order['token'] %>
          <div class="modal-body">
            <div class="form-group">
              <%= label_tag :id, 'Commande', class: 'col-form-label' %>
              <%= text_field_tag :id, @order['invoiceNumber'], autofocus: true, class: 'form-control', disabled: true %>
            </div>
            <div class="form-group">
              <%= label_tag :price, 'Prix', class: 'col-form-label' %>
              <%= text_field_tag :price, @order['finalGrandTotal'], class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= label_tag :message, 'Message', class: 'col-form-label' %>
              <%= text_area_tag :message, nil, class: 'form-control', rows: 4 %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= submit_tag 'Valider', class: 'btn btn-danger', data: { confirm: 'Êtes vous sur de vouloir rembourser la commande ?' } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="Contacter" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Contacter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag send_comment_periods_path, method: :post, remote: true do %>
          <%= hidden_field_tag 'token', @order['token'] %>
          <div class="modal-body">
            <div class="form-group">
              <%= label_tag :message, 'Message', class: 'col-form-label' %>
              <%= text_area_tag :message, nil, class: 'form-control', rows: 4 %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= submit_tag 'Valider', class: 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>