config/routes.rb
Rails.application.routes.draw do
  resources :periods, except: [:new] do
    collection do
      get 'new/:user_id', :to => "periods#new", :as => 'new'
      post 'status/(:token)', :to => "periods#order_status", :as => 'order_status'
      post 'refund/(:token)', :to => "periods#order_refund", :as => 'order_refund'
      post 'tracking/(:token)', :to => "periods#order_tracking", :as => 'order_tracking'
      post 'message/(:token)', :to => "periods#send_comment", :as => 'send_comment'
    end
  end

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users

  get '/dashboard' => "dashboard#index", as: :user_root
  get '/order/:id' => "dashboard#order", as: :order_dashboard
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  has_many :periods
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :periods, :update, :destroy]
  load_and_authorize_resource

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/1
  def show
  end


  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :index, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :admin, :email, :tracking_url, :password, :password_confirmation)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :user_firstname, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :user_lastname, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: 'form-control' %>
  </div>

  <div class="form-check">
    <%= form.check_box :admin, id: :user_admin, class: 'form-check-input' %>
    <%= form.label :admin, class: 'form-check-label' %>
  </div>

  <h3 class="display-6">Tracking URL</h3>

  <div class="form-group">
    <%= form.label :tracking_url %>
    <%= form.select :tracking_url, id: :user_tracking_url, class: 'form-control' do %>
      <%= options_for_select(tracking_url, selected: user.tracking_url) %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit 'Valider', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-8">
      <h1>Modifier l'utilisateur</h1>
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div id="dashboard">
  <div class="container user-management">
    <h2>Utilisateurs</h2>
    <%= link_to "Nouvel utilisateur", new_user_path %>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Admin</th>
            <th colspan="2" scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th scope="row"><%= user.id %></th>
              <td><%= user.firstname %></td>
              <td><%= user.lastname %></td>
              <td><%= user.admin ? "✅" : "❌" %></td>
              <td><%= link_to "Modifier", edit_user_path(user.id) %></td>
              <td><%= link_to "Periodes", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-8">
      <h1>Nouvel utilisateur</h1>
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/users/periods.html.erb
<div id="dashboard">
  <div class="container user-management">
    <h2>Périodes de <%= @user.firstname + ' ' + @user.lastname %></h2>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Début</th>
            <th scope="col">Fin</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.periods.each do |period| %>
            <tr>
              <td><%= period.start_date %></td>
              <td><%= period.end_date %></td>
              <td><%= link_to "Modifier", edit_period_path(period.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="dashboard">
  <div class="container user-management">
    <h2>Périodes de <%= @user.firstname + ' ' + @user.lastname %></h2>
    <%= link_to "Editer", edit_user_path(@user.id) %>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Début</th>
            <th scope="col">Fin</th>
            <th colspan="2" scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.periods.each do |period| %>
            <tr>
              <td><%= period.start_date %></td>
              <td><%= period.end_date %></td>
              <td><%= link_to "Modifier", edit_period_path(period.id) %></td>
              <td><%= button_to "Supprimer", period_path(period.id), method: :delete, class: "btn btn-danger", confirm: 'Are you sure?' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "Nouvelle période", new_periods_path(@user.id) %>
    </div>
  </div>
</div>