config/routes.rb
Rails.application.routes.draw do
  resources :periods, except: [:new] do
    collection do
      get 'new/:user_id', :to => "periods#new", :as => 'new'
      post 'status/(:token)', :to => "periods#order_status", :as => 'order_status'
      post 'refund/(:token)', :to => "periods#order_refund", :as => 'order_refund'
      post 'tracking/(:token)', :to => "periods#order_tracking", :as => 'order_tracking'
      post 'message/(:token)', :to => "periods#send_comment", :as => 'send_comment'
    end
  end

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users

  get '/dashboard' => "dashboard#index", as: :user_root
  get '/order/:id' => "dashboard#order", as: :order_dashboard
end

app/helpers/layout_helper.rb
module LayoutHelper

  def status_translate(s = false)
    status = {
      InProgress: 'En cours',
      Processed: 'Traitée',
      Disputed: 'Contestée',
      Shipped: 'Expédiée',
      Delivered: 'Livrée',
      Pending: 'En attente',
      Cancelled: 'Annulée'
    }.with_indifferent_access
    unless s == false
      return status[s]
    else
      return status
    end
  end

  def actions_status(s, id)
    conditions = {
      InProgress: 'Processed',
      Processed: 'Shipped',
      Disputed: 'Cancelled',
      Shipped: 'Delivered',
      Delivered: false,
      Pending: 'InProgress',
      Cancelled: 'InProgress'
    }
    conditions.each do |k, v|
      if s.downcase == k.to_s.downcase && v != false
        return button_to status_translate(v), {controller: 'periods', action: 'order_status', token: id, status: v}, method: :post, remote: true, class: 'btn btn-warning', data: { confirm: 'Êtes vous sur de vouloir modifier le statut ?' }
      end
    end
    return ''
  end

end

app/views/layouts/partials/_header.html.erb
<% if user_signed_in? %>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mr-auto">
      <%= link_to 'Capsule', 'https://capsule-bordeaux.fr', class: 'navbar-brand', target: '_blank' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav  mr-auto">
          <li class="nav-item">
            <%= link_to 'Accueil', root_path, class: cp('/dashboard', 'nav-link') %>
          </li>
          <li class="nav-item">
            <%= link_to 'Periodes', periods_path, class: cp(periods_path, 'nav-link') %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if current_user.admin %>
            <li class="nav-item">
              <%= link_to 'Utilisateurs', users_path, class: cp(users_path, 'nav-link') %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= button_to 'Se déconnecter', destroy_user_session_path, :method => :delete, class: 'btn btn-danger' %>
          </li>
        </ul>
      </div>
    </nav>
  </header>
<% end %>
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>